name: "新功能提案"
description: "添加一个新功能或内容"
labels: [· 新功能, 新反馈]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已在 [Issues 页面](https://github.com/YUANXINGlingyun/cchtml/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述你想添加的功能具体是怎样的。"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 原因
    description: "详细描述你为什么需要这项功能，这有助于开发者评估它的优先度。"
  validations:
    required: true
